### ISSUE TITLE
don't support mongodb 3.0

### ISSUE THREAD

**Issue by superleemo** [quokkaproject/quokka#291] opened 2015-08-23 08:12 UTC
I want to use mongodb 3.0,so I upgraded the mongoengine and pymongo ，but “get_or_create” method is deprecated in mongoengine's latest version! how can i fix it?

**Comment by rochacbruno** [comment] 2015-08-23 14:51
HI @fxxku I am going to check this, replace get_or_create with an internal method

**Comment by rochacbruno** [comment] 2015-08-23 15:17
@fxxku it should be fixed, can you please try again and please report if there is any other issue.

Thanks

**Closed as completed** 2015-08-23 15:17 UTC
Labels: bug

**Comment by oktools** [comment] 2015-09-12 15:23
Is it possible this issue needs to be re-opened? (or opened as a new issue? -- my problem is not the same as the the original poster's)

In my case, I noticed I couldn't connect to my MongoLab account. It's my understanding that MongoDB 3 requires the PyMongo3+. And as is noted in requirements.txt, MongoEngine is not yet compatible with the needed PyMongo.

If this is correct, then at a minimum, the installation and hosting sections of README.rst should indicate accordingly. I'm pretty sure Docker Hub's official mongodb image is version 3, as is MongoLab's free account (and possibly others).

**Comment by rochacbruno** [comment] 2015-09-14 01:30
I am using Mongo3 with Pymongo 2.8 and Mongoengine. Everything is working nice, except by the authentication part.

The problem is only because of the changes in auth.

We can open a new issue and investigate better how to handle this issue, I wanted to upgrade to PyMongo 3.x but on my tests a lot of things got messed up.

**Comment by oktools** [comment] 2015-09-14 04:32
what, in your estimation, is the bottleneck in mongoengine's handling of
pymongo3? and how integral is it (compared to accessing pymongo directly)
in quokka?

Thank you.

Danny
