### ISSUE TITLE
can't delete role 

### ISSUE THREAD

**Issue by superleemo** [quokkaproject/quokka#305] opened 2015-10-05 02:39 UTC
I created a new channel,and set an admin role,but after a while i don't want admin role ,so i delete the admin role in edit pannel and set role to none,but it doesn't work,and it still need an admin role,so i think this is a bug!

**Comment by oktools** [comment] 2015-10-26 12:05
I can confirm that once a role is selected for a new or pre-existing channel, the "x" for removing it does not function fully. If the channel document has been saved with a role, it can no longer be saved without one -- it just keeps coming back. It can be switched to another role, or removed from a list of roles. 

These results were obtained using the most recent commit (8c5d96d).

**Comment by rochacbruno** [comment] 2015-10-26 12:29
OK, thanks for reposting. I will take a look today.

**Comment by counsellors** [comment] 2016-08-29 04:28
I meet the same problem, when the field looks like somethings = ListField(ReferenceField(SomeModel)), and the selected option couldn't be remove. Is it fixed in the new version ?

**Comment by counsellors** [comment] 2016-08-29 11:20
It's be soveled. Because that I used an old version of quokka with flask-mongoengine-0.7.4,  and the problem has been found in [#148](https://github.com/MongoEngine/flask-mongoengine/issues/148).

**Closed as completed** 2018-02-06 13:46 UTC
Labels: bug
