### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by kgshv** [quokkaproject/quokka#304] opened 2015-09-23 08:21 UTC
Installed following your tutorial on main repo page on GitHub. Installed system dependencies and all python packages. Set up the database. When running python manage.py runserver --host 0.0.0.0 --port 5000 I get the message "No handlers could be found for logger "root" in console, but the server starts.

http://localhost:5000/ opens up just fine.

When I open http://localhost:5000/admin/, I get this error thread:

TypeError
TypeError: 'bool' object is not callable

Traceback (most recent call last)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
return self.wsgi_app(environ, start_response)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/roman/.venvs/native/lib/python2.7/site-packages/flask_admin/base.py", line 64, in inner
abort = self._handle_view(f.__name__, **kwargs)
File "/home/roman/Downloads/TEMP/quokka/quokka/core/admin/models.py", line 53, in _handle_view
if not current_user.is_authenticated():
TypeError: 'bool' object is not callable

**Comment by wangyishuai007** [comment] 2015-09-25 09:13
Reference #301

**Comment by QiXuanWang** [comment] 2015-10-28 02:37
#301  is closed but I saw it too with latest version. Is the fix reflected in main branch?

**Comment by rochacbruno** [comment] 2015-10-28 02:47
yes. pip install flask-login<3 fixed it.

**Comment by rochacbruno** [comment] 2015-10-28 02:49
the problem is because flask login 3.x breaks compatibility as they changed that method to a property.

So we have to use flasklogin version older than 3.x until it gets fixed in flask security and templates

**Comment by QiXuanWang** [comment] 2015-10-28 02:54
OK. I'm always curious why don't you add "flask-login<3" as well as other packages like "Jinja2"(with version) into requirements.txt ? I'm not an expert on PIP but it seems they will not be installed automatically?

**Comment by rochacbruno** [comment] 2015-10-28 16:15
@QiXuanWang Done! https://github.com/quokkaproject/quokka/blob/development/requirements/requirements.txt#L28

**Closed as completed** 2015-10-28 16:15 UTC
